runtime: nodejs16

handlers:
  - url: task-dicoding-gcp/styles
    static_dir: task-dicoding-gcp/styles

  - url: /
    static_files: task-dicoding-gcp/index.html
    upload: task-dicoding-gcp/index.html
    
  - url: /(.*)
    static_files: task-dicoding-gcp/\1
    upload: task-dicoding-gcp/(.*)
